analyzer:
  exclude:
    - '**.g.dart' # Ignora arquivos gerados automaticamente

  errors:
    missing_return: error
    dead_code: warning
    unnecessary_cast: warning
    avoid_print: error
    prefer_const_constructors: error

linter:
  rules:
    - avoid_print
    - avoid_classes_with_only_static_members
    - prefer_final_fields
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_expression_function_bodies
    - prefer_relative_imports
    - prefer_interpolation_to_compose_strings
    - sort_constructors_first
    - unnecessary_this
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
