name: marvel_project
description: 'A Marvel Project'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  http: ^0.13.5
  crypto: ^3.0.6
  connectivity_plus: ^6.1.3
  get_it: ^8.0.3
  json_annotation: ^4.7.0
  safe_device: ^1.2.1
  retrofit: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^5.0.0
  json_serializable: ^6.1.4
  mockito: ^5.4.5
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true
  assets:
    - lib/shared/assets/images/
