name: marvel_project
description: 'A Marvel Project'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.0.0
  connectivity_plus: ^6.1.3
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.4
  http: ^0.13.5
  json_annotation: ^4.7.0
  retrofit: ^4.4.2
  safe_device: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^5.0.0
  json_serializable: ^6.1.4
  mockito: ^5.4.5
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true
  assets:
    - lib/shared/assets/images/
    - .env

flutter_native_splash:
  color: '#000000'
  image: 'lib/shared/assets/images/marvel_logo.png'
  android: true
  ios: true
  web: false
